/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    'case-studies': CaseStudy;
    partners: Partner;
    posts: Post;
    leads: Lead;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super Admin = full control. Admin = content + leads. Editor = drafts + own posts.
   */
  role: 'super_admin' | 'admin' | 'editor';
  /**
   * Optional profile picture.
   */
  avatar?: (number | null) | Media;
  /**
   * Uncheck to disable login without deleting the user record.
   */
  isActive?: boolean | null;
  lastLoginAt?: string | null;
  loginCount?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Used as the image alt attribute. Required for accessibility.
   */
  altText: string;
  /**
   * Optional caption rendered below an image when used inside an article.
   */
  caption?: string | null;
  /**
   * Photographer / source credit, if any.
   */
  credit?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path (e.g. "about-us", "publish-with-us/advertise"). No leading slash.
   */
  slug: string;
  modules?:
    | (
        | {
            /**
             * Small label above the H1 (e.g. "LIVE · AI VISIBILITY ENGINE").
             */
            badge?: string | null;
            h1: string;
            /**
             * Portion of H1 to render in accent colour.
             */
            h1Highlight?: string | null;
            subtitle?: string | null;
            image?: (number | null) | Media;
            ctas?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'outline' | 'text') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            sub?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  previewVariant?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilities';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  num: string;
                  label: string;
                  sub?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  q: string;
                  a: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqs';
          }
        | {
            title: string;
            subtitle?: string | null;
            ctaLabel: string;
            ctaHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-band';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            image: number | Media;
            caption?: string | null;
            size?: ('narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  /**
                   * e.g. "Month 1".
                   */
                  phase?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process-steps';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  /**
                   * Emoji token (e.g. "🛡️") — maps to Lucide via <Glyph>.
                   */
                  iconToken?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
      )[]
    | null;
  /**
   * How this piece of content is engineered to be discovered and cited by AI answer engines.
   */
  aiVisibility?: {
    /**
     * Brand/entity name AI should associate with this content (e.g. "SecurityBlogs").
     */
    entityName?: string | null;
    /**
     * One-sentence topic AI uses to categorise the page.
     */
    primaryTopic?: string | null;
    targetEngines?: ('chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai')[] | null;
    targetQueryTypes?: ('informational' | 'commercial' | 'transactional' | 'comparison' | 'navigational')[] | null;
    keywordsToWin?:
      | {
          keyword: string;
          /**
           * Leave blank if unknown.
           */
          currentPosition?: number | null;
          id?: string | null;
        }[]
      | null;
    quotedPassages?:
      | {
          /**
           * The exact wording AI overviews should quote.
           */
          passage: string;
          /**
           * Optional id attribute on the matching DOM element so the passage is addressable.
           */
          anchorId?: string | null;
          id?: string | null;
        }[]
      | null;
    entityRelationships?:
      | {
          relatedEntity: string;
          relationshipType?: ('publishes' | 'authored_by' | 'about' | 'cites' | 'part_of' | 'same_as') | null;
          id?: string | null;
        }[]
      | null;
    competingUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    lastAuditAt?: string | null;
    auditResults?:
      | {
          platform: 'chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai';
          cited?: boolean | null;
          /**
           * Position within the AI answer if cited (1 = primary citation).
           */
          position?: number | null;
          /**
           * Archive.org or screenshot URL.
           */
          snapshotUrl?: string | null;
          checkedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Override <title>. Leave blank to use the document title.
     */
    seoTitleOverride?: string | null;
    /**
     * Override <meta description>.
     */
    seoDescriptionOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Advanced: arbitrary additions/overrides to the JSON-LD this page emits.
     */
    schemaOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL slug — must match /services/<slug>/ on the marketing site.
   */
  slug: string;
  /**
   * One-line catalogue description.
   */
  shortDesc: string;
  /**
   * Hero lead paragraph on the service detail page.
   */
  intro?: string | null;
  /**
   * e.g. "AI OPTIMISATION" — the small chip above the H1.
   */
  heroBadge?: string | null;
  /**
   * Hex colour for the brand chip + accent text. Default: brand blue.
   */
  accentColor?: string | null;
  /**
   * Hero image / og:image for the service.
   */
  cover?: (number | null) | Media;
  capabilities?:
    | {
        title: string;
        description: string;
        /**
         * Which themed live preview component renders on this card.
         */
        previewVariant?:
          | (
              | 'schema'
              | 'semantic'
              | 'structured-data'
              | 'signal-meters'
              | 'freshness'
              | 'citations'
              | 'answer-box'
              | 'featured-snippet'
              | 'faq-schema'
              | 'voice'
              | 'ai-overview'
              | 'eeat'
              | 'on-page'
              | 'technical-seo'
              | 'local-seo'
              | 'content-cluster'
              | 'backlinks'
              | 'rank-tracking'
              | 'keywords'
              | 'geo-target'
              | 'bid'
              | 'funnel'
              | 'remarketing'
              | 'auction'
              | 'linkedin'
              | 'cpc'
              | 'b2b'
              | 'clarity'
              | 'journey'
              | 'browser'
              | 'wp-editor'
              | 'cwv'
              | 'uptime'
              | 'schema-graph'
              | 'before-after'
              | 'entity-card'
              | 'knowledge-panel'
              | 'signal-distribution'
              | 'cross-platform'
              | 'nap'
              | 'confirmation'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        title: string;
        description: string;
        /**
         * Optional themed visual for this step (see Capabilities for options).
         */
        previewVariant?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        /**
         * Display value, e.g. "87%" or "3.2×".
         */
        num: string;
        label: string;
        /**
         * Optional sub-line, e.g. "+62% vs baseline".
         */
        sub?: string | null;
        trend?: ('up' | 'flat' | 'down') | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Single chip shown on the /services/ catalogue card (e.g. "+180% organic traffic").
   */
  statChip?: string | null;
  /**
   * How this piece of content is engineered to be discovered and cited by AI answer engines.
   */
  aiVisibility?: {
    /**
     * Brand/entity name AI should associate with this content (e.g. "SecurityBlogs").
     */
    entityName?: string | null;
    /**
     * One-sentence topic AI uses to categorise the page.
     */
    primaryTopic?: string | null;
    targetEngines?: ('chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai')[] | null;
    targetQueryTypes?: ('informational' | 'commercial' | 'transactional' | 'comparison' | 'navigational')[] | null;
    keywordsToWin?:
      | {
          keyword: string;
          /**
           * Leave blank if unknown.
           */
          currentPosition?: number | null;
          id?: string | null;
        }[]
      | null;
    quotedPassages?:
      | {
          /**
           * The exact wording AI overviews should quote.
           */
          passage: string;
          /**
           * Optional id attribute on the matching DOM element so the passage is addressable.
           */
          anchorId?: string | null;
          id?: string | null;
        }[]
      | null;
    entityRelationships?:
      | {
          relatedEntity: string;
          relationshipType?: ('publishes' | 'authored_by' | 'about' | 'cites' | 'part_of' | 'same_as') | null;
          id?: string | null;
        }[]
      | null;
    competingUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    lastAuditAt?: string | null;
    auditResults?:
      | {
          platform: 'chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai';
          cited?: boolean | null;
          /**
           * Position within the AI answer if cited (1 = primary citation).
           */
          position?: number | null;
          /**
           * Archive.org or screenshot URL.
           */
          snapshotUrl?: string | null;
          checkedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Override <title>. Leave blank to use the document title.
     */
    seoTitleOverride?: string | null;
    /**
     * Override <meta description>.
     */
    seoDescriptionOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Advanced: arbitrary additions/overrides to the JSON-LD this page emits.
     */
    schemaOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'archived';
  /**
   * Lower number = earlier in the catalogue.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Marketing-friendly title — e.g. "ShieldTech Security — Full Service".
   */
  headline: string;
  slug: string;
  /**
   * Client name shown on the card.
   */
  clientName: string;
  /**
   * Optional link to the Partner record for this client.
   */
  partner?: (number | null) | Partner;
  /**
   * Which service line delivered this outcome.
   */
  service?: (number | null) | Service;
  clientLogo?: (number | null) | Media;
  /**
   * Hero image at the top of the case-study detail page.
   */
  cover?: (number | null) | Media;
  /**
   * One-paragraph summary used on the /case-studies/ index card.
   */
  summary: string;
  /**
   * Full case-study narrative — challenge, approach, outcome.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Headline metrics shown as stat tiles on the case-study page.
   */
  results?:
    | {
        /**
         * e.g. "Organic traffic".
         */
        metric: string;
        /**
         * e.g. "+340%".
         */
        value: string;
        /**
         * Optional sub-line context.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Lower number = earlier in the case-studies grid.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  /**
   * How this piece of content is engineered to be discovered and cited by AI answer engines.
   */
  aiVisibility?: {
    /**
     * Brand/entity name AI should associate with this content (e.g. "SecurityBlogs").
     */
    entityName?: string | null;
    /**
     * One-sentence topic AI uses to categorise the page.
     */
    primaryTopic?: string | null;
    targetEngines?: ('chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai')[] | null;
    targetQueryTypes?: ('informational' | 'commercial' | 'transactional' | 'comparison' | 'navigational')[] | null;
    keywordsToWin?:
      | {
          keyword: string;
          /**
           * Leave blank if unknown.
           */
          currentPosition?: number | null;
          id?: string | null;
        }[]
      | null;
    quotedPassages?:
      | {
          /**
           * The exact wording AI overviews should quote.
           */
          passage: string;
          /**
           * Optional id attribute on the matching DOM element so the passage is addressable.
           */
          anchorId?: string | null;
          id?: string | null;
        }[]
      | null;
    entityRelationships?:
      | {
          relatedEntity: string;
          relationshipType?: ('publishes' | 'authored_by' | 'about' | 'cites' | 'part_of' | 'same_as') | null;
          id?: string | null;
        }[]
      | null;
    competingUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    lastAuditAt?: string | null;
    auditResults?:
      | {
          platform: 'chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai';
          cited?: boolean | null;
          /**
           * Position within the AI answer if cited (1 = primary citation).
           */
          position?: number | null;
          /**
           * Archive.org or screenshot URL.
           */
          snapshotUrl?: string | null;
          checkedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Override <title>. Leave blank to use the document title.
     */
    seoTitleOverride?: string | null;
    /**
     * Override <meta description>.
     */
    seoDescriptionOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Advanced: arbitrary additions/overrides to the JSON-LD this page emits.
     */
    schemaOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Lowercase + hyphens.
   */
  slug: string;
  type: 'client' | 'partner' | 'integrator' | 'vendor' | 'community';
  region?: ('AU' | 'US' | 'GB' | 'AE' | 'SG' | 'other') | null;
  /**
   * Short blurb shown on listings + the directory page.
   */
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Square logo, transparent background preferred.
   */
  logo?: (number | null) | Media;
  /**
   * Optional cover image used on the partner detail page.
   */
  cover?: (number | null) | Media;
  /**
   * Partner website URL.
   */
  website?: string | null;
  /**
   * Optional primary contact email (kept private — not rendered publicly).
   */
  contactEmail?: string | null;
  /**
   * Which of our service lines this partner uses (or delivers).
   */
  services?: (number | Service)[] | null;
  /**
   * Featured case study for this partner, if any.
   */
  caseStudy?: (number | null) | CaseStudy;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Featured partners surface on the homepage + directory hero.
   */
  isFeatured?: boolean | null;
  /**
   * Lower number = higher on the directory.
   */
  sortOrder?: number | null;
  status: 'active' | 'inactive' | 'archived';
  /**
   * How this piece of content is engineered to be discovered and cited by AI answer engines.
   */
  aiVisibility?: {
    /**
     * Brand/entity name AI should associate with this content (e.g. "SecurityBlogs").
     */
    entityName?: string | null;
    /**
     * One-sentence topic AI uses to categorise the page.
     */
    primaryTopic?: string | null;
    targetEngines?: ('chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai')[] | null;
    targetQueryTypes?: ('informational' | 'commercial' | 'transactional' | 'comparison' | 'navigational')[] | null;
    keywordsToWin?:
      | {
          keyword: string;
          /**
           * Leave blank if unknown.
           */
          currentPosition?: number | null;
          id?: string | null;
        }[]
      | null;
    quotedPassages?:
      | {
          /**
           * The exact wording AI overviews should quote.
           */
          passage: string;
          /**
           * Optional id attribute on the matching DOM element so the passage is addressable.
           */
          anchorId?: string | null;
          id?: string | null;
        }[]
      | null;
    entityRelationships?:
      | {
          relatedEntity: string;
          relationshipType?: ('publishes' | 'authored_by' | 'about' | 'cites' | 'part_of' | 'same_as') | null;
          id?: string | null;
        }[]
      | null;
    competingUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    lastAuditAt?: string | null;
    auditResults?:
      | {
          platform: 'chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai';
          cited?: boolean | null;
          /**
           * Position within the AI answer if cited (1 = primary citation).
           */
          position?: number | null;
          /**
           * Archive.org or screenshot URL.
           */
          snapshotUrl?: string | null;
          checkedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Override <title>. Leave blank to use the document title.
     */
    seoTitleOverride?: string | null;
    /**
     * Override <meta description>.
     */
    seoDescriptionOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Advanced: arbitrary additions/overrides to the JSON-LD this page emits.
     */
    schemaOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL slug. Lowercase, hyphens only. Auto-suggested from title.
   */
  slug: string;
  category:
    | 'blog'
    | 'industry-news'
    | 'security-guides'
    | 'research-reports'
    | 'security-industry-seo'
    | 'security-trends-2026';
  /**
   * Short summary used on listing pages + AI overviews.
   */
  excerpt: string;
  /**
   * Hero image at the top of the article + listing thumbnails.
   */
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimated read time. Auto-calculated on save.
   */
  readingMinutes?: number | null;
  viewCount?: number | null;
  status: 'draft' | 'scheduled' | 'published' | 'archived';
  /**
   * Set in the future to schedule. Auto-filled on first publish.
   */
  publishedAt?: string | null;
  /**
   * How this piece of content is engineered to be discovered and cited by AI answer engines.
   */
  aiVisibility?: {
    /**
     * Brand/entity name AI should associate with this content (e.g. "SecurityBlogs").
     */
    entityName?: string | null;
    /**
     * One-sentence topic AI uses to categorise the page.
     */
    primaryTopic?: string | null;
    targetEngines?: ('chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai')[] | null;
    targetQueryTypes?: ('informational' | 'commercial' | 'transactional' | 'comparison' | 'navigational')[] | null;
    keywordsToWin?:
      | {
          keyword: string;
          /**
           * Leave blank if unknown.
           */
          currentPosition?: number | null;
          id?: string | null;
        }[]
      | null;
    quotedPassages?:
      | {
          /**
           * The exact wording AI overviews should quote.
           */
          passage: string;
          /**
           * Optional id attribute on the matching DOM element so the passage is addressable.
           */
          anchorId?: string | null;
          id?: string | null;
        }[]
      | null;
    entityRelationships?:
      | {
          relatedEntity: string;
          relationshipType?: ('publishes' | 'authored_by' | 'about' | 'cites' | 'part_of' | 'same_as') | null;
          id?: string | null;
        }[]
      | null;
    competingUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    lastAuditAt?: string | null;
    auditResults?:
      | {
          platform: 'chatgpt' | 'perplexity' | 'gemini' | 'claude' | 'bing_copilot' | 'google_ai';
          cited?: boolean | null;
          /**
           * Position within the AI answer if cited (1 = primary citation).
           */
          position?: number | null;
          /**
           * Archive.org or screenshot URL.
           */
          snapshotUrl?: string | null;
          checkedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Override <title>. Leave blank to use the document title.
     */
    seoTitleOverride?: string | null;
    /**
     * Override <meta description>.
     */
    seoDescriptionOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Advanced: arbitrary additions/overrides to the JSON-LD this page emits.
     */
    schemaOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  displayTitle?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  message?: string | null;
  /**
   * Source-form-specific data — keep for audit.
   */
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'new' | 'contacted' | 'qualified' | 'proposal_sent' | 'nurturing' | 'won' | 'lost' | 'spam';
  lifecycleStage?: ('subscriber' | 'lead' | 'mql' | 'sql' | 'customer' | 'evangelist') | null;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  /**
   * Who owns this lead. Email notification sent on assignment.
   */
  assignedTo?: (number | null) | User;
  valueEstimate?: number | null;
  nextActionAt?: string | null;
  nextActionNote?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Chronological log of every interaction with this lead.
   */
  timeline?:
    | {
        at: string;
        byUser?: (number | null) | User;
        type: 'status_change' | 'note' | 'email_sent' | 'email_received' | 'call' | 'meeting' | 'assignment';
        note: string;
        id?: string | null;
      }[]
    | null;
  wonAt?: string | null;
  wonValue?: number | null;
  lostAt?: string | null;
  lostReason?: ('no_response' | 'price' | 'timing' | 'competitor' | 'out_of_scope' | 'not_a_fit' | 'other') | null;
  lostNotes?: string | null;
  source: 'contact-form' | 'career' | 'guest-post' | 'visibility-challenge' | 'visibility-checker' | 'manual' | 'other';
  ip?: string | null;
  userAgent?: string | null;
  referrer?: string | null;
  /**
   * If non-empty, this was likely a bot.
   */
  honeypot?: string | null;
  turnstileToken?: string | null;
  /**
   * Page the form was submitted from.
   */
  pageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path or regex to match (e.g. "/aio/" or "^/blog/(.+)$"). Must start with a slash.
   */
  fromPath: string;
  /**
   * Destination path. Use $1 / $2 backreferences for regex captures.
   */
  toPath: string;
  statusCode: '301' | '302' | '307' | '308';
  /**
   * Tick if `fromPath` is a regular expression rather than a literal path.
   */
  isRegex?: boolean | null;
  isActive?: boolean | null;
  /**
   * Auto-incremented by the redirect middleware.
   */
  hitCount?: number | null;
  lastHitAt?: string | null;
  /**
   * Why this redirect exists. Helps future-you remember.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  isActive?: T;
  lastLoginAt?: T;
  loginCount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  caption?: T;
  credit?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  modules?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              h1?: T;
              h1Highlight?: T;
              subtitle?: T;
              image?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilities?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              sub?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    previewVariant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    num?: T;
                    label?: T;
                    sub?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqs?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    q?: T;
                    a?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cta-band'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        'process-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    phase?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    iconToken?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  aiVisibility?:
    | T
    | {
        entityName?: T;
        primaryTopic?: T;
        targetEngines?: T;
        targetQueryTypes?: T;
        keywordsToWin?:
          | T
          | {
              keyword?: T;
              currentPosition?: T;
              id?: T;
            };
        quotedPassages?:
          | T
          | {
              passage?: T;
              anchorId?: T;
              id?: T;
            };
        entityRelationships?:
          | T
          | {
              relatedEntity?: T;
              relationshipType?: T;
              id?: T;
            };
        competingUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        lastAuditAt?: T;
        auditResults?:
          | T
          | {
              platform?: T;
              cited?: T;
              position?: T;
              snapshotUrl?: T;
              checkedAt?: T;
              id?: T;
            };
        seoTitleOverride?: T;
        seoDescriptionOverride?: T;
        ogImage?: T;
        schemaOverrides?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDesc?: T;
  intro?: T;
  heroBadge?: T;
  accentColor?: T;
  cover?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        previewVariant?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        previewVariant?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        num?: T;
        label?: T;
        sub?: T;
        trend?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  statChip?: T;
  aiVisibility?:
    | T
    | {
        entityName?: T;
        primaryTopic?: T;
        targetEngines?: T;
        targetQueryTypes?: T;
        keywordsToWin?:
          | T
          | {
              keyword?: T;
              currentPosition?: T;
              id?: T;
            };
        quotedPassages?:
          | T
          | {
              passage?: T;
              anchorId?: T;
              id?: T;
            };
        entityRelationships?:
          | T
          | {
              relatedEntity?: T;
              relationshipType?: T;
              id?: T;
            };
        competingUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        lastAuditAt?: T;
        auditResults?:
          | T
          | {
              platform?: T;
              cited?: T;
              position?: T;
              snapshotUrl?: T;
              checkedAt?: T;
              id?: T;
            };
        seoTitleOverride?: T;
        seoDescriptionOverride?: T;
        ogImage?: T;
        schemaOverrides?: T;
      };
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  headline?: T;
  slug?: T;
  clientName?: T;
  partner?: T;
  service?: T;
  clientLogo?: T;
  cover?: T;
  summary?: T;
  body?: T;
  results?:
    | T
    | {
        metric?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  sortOrder?: T;
  publishedAt?: T;
  aiVisibility?:
    | T
    | {
        entityName?: T;
        primaryTopic?: T;
        targetEngines?: T;
        targetQueryTypes?: T;
        keywordsToWin?:
          | T
          | {
              keyword?: T;
              currentPosition?: T;
              id?: T;
            };
        quotedPassages?:
          | T
          | {
              passage?: T;
              anchorId?: T;
              id?: T;
            };
        entityRelationships?:
          | T
          | {
              relatedEntity?: T;
              relationshipType?: T;
              id?: T;
            };
        competingUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        lastAuditAt?: T;
        auditResults?:
          | T
          | {
              platform?: T;
              cited?: T;
              position?: T;
              snapshotUrl?: T;
              checkedAt?: T;
              id?: T;
            };
        seoTitleOverride?: T;
        seoDescriptionOverride?: T;
        ogImage?: T;
        schemaOverrides?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  region?: T;
  summary?: T;
  body?: T;
  logo?: T;
  cover?: T;
  website?: T;
  contactEmail?: T;
  services?: T;
  caseStudy?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  isFeatured?: T;
  sortOrder?: T;
  status?: T;
  aiVisibility?:
    | T
    | {
        entityName?: T;
        primaryTopic?: T;
        targetEngines?: T;
        targetQueryTypes?: T;
        keywordsToWin?:
          | T
          | {
              keyword?: T;
              currentPosition?: T;
              id?: T;
            };
        quotedPassages?:
          | T
          | {
              passage?: T;
              anchorId?: T;
              id?: T;
            };
        entityRelationships?:
          | T
          | {
              relatedEntity?: T;
              relationshipType?: T;
              id?: T;
            };
        competingUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        lastAuditAt?: T;
        auditResults?:
          | T
          | {
              platform?: T;
              cited?: T;
              position?: T;
              snapshotUrl?: T;
              checkedAt?: T;
              id?: T;
            };
        seoTitleOverride?: T;
        seoDescriptionOverride?: T;
        ogImage?: T;
        schemaOverrides?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readingMinutes?: T;
  viewCount?: T;
  status?: T;
  publishedAt?: T;
  aiVisibility?:
    | T
    | {
        entityName?: T;
        primaryTopic?: T;
        targetEngines?: T;
        targetQueryTypes?: T;
        keywordsToWin?:
          | T
          | {
              keyword?: T;
              currentPosition?: T;
              id?: T;
            };
        quotedPassages?:
          | T
          | {
              passage?: T;
              anchorId?: T;
              id?: T;
            };
        entityRelationships?:
          | T
          | {
              relatedEntity?: T;
              relationshipType?: T;
              id?: T;
            };
        competingUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        lastAuditAt?: T;
        auditResults?:
          | T
          | {
              platform?: T;
              cited?: T;
              position?: T;
              snapshotUrl?: T;
              checkedAt?: T;
              id?: T;
            };
        seoTitleOverride?: T;
        seoDescriptionOverride?: T;
        ogImage?: T;
        schemaOverrides?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  displayTitle?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  extras?: T;
  status?: T;
  lifecycleStage?: T;
  priority?: T;
  assignedTo?: T;
  valueEstimate?: T;
  nextActionAt?: T;
  nextActionNote?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        at?: T;
        byUser?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  wonAt?: T;
  wonValue?: T;
  lostAt?: T;
  lostReason?: T;
  lostNotes?: T;
  source?: T;
  ip?: T;
  userAgent?: T;
  referrer?: T;
  honeypot?: T;
  turnstileToken?: T;
  pageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  isRegex?: T;
  isActive?: T;
  hitCount?: T;
  lastHitAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Sitewide configuration: brand, contact, social, SEO defaults, analytics, footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logoHeader?: (number | null) | Media;
  logoFooter?: (number | null) | Media;
  /**
   * Favicon-sized square logo.
   */
  logoSquare?: (number | null) | Media;
  /**
   * Default OpenGraph image used when a page has no override.
   */
  ogImageDefault?: (number | null) | Media;
  contactEmail: string;
  contactPhone?: string | null;
  businessHours?: string | null;
  addressCountry?: string | null;
  areaServed?: ('AU' | 'US' | 'GB' | 'AE' | 'SG')[] | null;
  social?:
    | {
        platform: 'linkedin' | 'facebook' | 'instagram' | 'youtube' | 'x' | 'tiktok' | 'other';
        url: string;
        /**
         * Optional display label.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  acknowledgement?: string | null;
  /**
   * Aboriginal + Torres Strait Islander flags composite image.
   */
  acknowledgementFlags?: (number | null) | Media;
  copyrightText?: string | null;
  defaultMetaTitle?: string | null;
  /**
   * Appended to every page title.
   */
  titleSuffix?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  twitterHandle?: string | null;
  /**
   * Used in <html lang=...> + JSON-LD inLanguage.
   */
  languageLocale?: string | null;
  /**
   * Google Tag Manager container ID. Leave blank to disable.
   */
  gtmId?: string | null;
  /**
   * URL of your self-hosted Plausible instance (e.g. https://stats.securityblogs.com.au). Leave blank to disable.
   */
  plausibleUrl?: string | null;
  plausibleDomain?: string | null;
  /**
   * Time slots shown on /book-strategy-call/.
   */
  bookingSlots?:
    | {
        /**
         * e.g. "Tue 10:00 AM".
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  cookieBannerEnabled?: boolean | null;
  cookieBannerText?: string | null;
  cookieBannerButton?: string | null;
  /**
   * Toggle ON to show a "be right back" page sitewide. Only Super Admins can flip this.
   */
  maintenanceMode?: boolean | null;
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logoHeader?: T;
  logoFooter?: T;
  logoSquare?: T;
  ogImageDefault?: T;
  contactEmail?: T;
  contactPhone?: T;
  businessHours?: T;
  addressCountry?: T;
  areaServed?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  acknowledgement?: T;
  acknowledgementFlags?: T;
  copyrightText?: T;
  defaultMetaTitle?: T;
  titleSuffix?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  languageLocale?: T;
  gtmId?: T;
  plausibleUrl?: T;
  plausibleDomain?: T;
  bookingSlots?:
    | T
    | {
        label?: T;
        id?: T;
      };
  cookieBannerEnabled?: T;
  cookieBannerText?: T;
  cookieBannerButton?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}